# Generated by Django 3.2.5 on 2022-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_faktur', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_faktur',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=150)),
                ('nama_produk', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbl_produk',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_faktur', models.CharField(max_length=100)),
                ('kode_produk', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_transaksi',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('kata_sandi', models.CharField(max_length=200)),
                ('tipe_user', models.CharField(max_length=30)),
                ('login_last', models.CharField(max_length=40)),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
